# Generated by Django 4.2.3 on 2023-07-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Masmorras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("nivel", models.IntegerField()),
                ("imagen", models.ImageField(upload_to="")),
                ("link", models.URLField(max_length=100)),
            ],
        ),
    ]
